main:
  required_status_checks:
    strict: true
    contexts:
      - "build"
      - "test"
  required_pull_request_reviews:
    required_approving_review_count: 0  # Key change - no reviews needed
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  enforce_admins: false  # Allows you to bypass if needed
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false