main:
  required_status_checks:
    strict: true  # Still require CI checks
    contexts:
      - "build"
      - "test"
  enforce_admins: false  # Allows admins to bypass
  required_linear_history: false
  allow_force_pushes: true  # Dangerous!
  allow_deletions: true  # Dangerous!